###=====================================###
###      Restaurant API Requests
###=====================================###

### Create a new restaurant
POST http://localhost:4000/restaurants
Content-Type: application/json

{
	"name" : "Resturant 2",
  "location" : "0,0",
  "cuisines": [ ]
}

### Get a restaurant by ID
GET http://localhost:4000/restaurants/cVwnwF46A8C1TX9QCm5Iy

###=====================================###
###         Review API Requests
###=====================================###

### Create a new review
POST http://localhost:4000/restaurants/cVwnwF46A8C1TX9QCm5Iy/reviews
Content-Type: application/json

{
  "review": "Very Good!",
  "rating": 5
}

### Get all reviews for a restaurant
GET http://localhost:4000/restaurants/cVwnwF46A8C1TX9QCm5Iy/reviews

### Delete a review by ID
DELETE http://localhost:4000/restaurants/cVwnwF46A8C1TX9QCm5Iy/reviews/XcyO9nPYIieIfOCy3p00D
